// 1 :- Create a program that asks the user to enter their name and their age.
// Print out a message that tells how many years they have to be 100 years old.
// 2 :- not complete./////
// 3 :- Create a program that asks the user for a number and then prints out a list of all the divisors of that number.
// 4 :- Take two lists, for example:
// a = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]
// b = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
// and write a program that returns a list that contains only the elements that are common between them (without duplicates).
// Make sure your program works on two lists of different sizes.
// 5 :- Write a Dart code that takes this list and makes a new list that has only the even elements of this list in it.
// 6 :- Write a Dart code that takes this list and makes a new list that has only the odd elements of this list in it.
// 7 :- Generate a random number between 1 and 100. Ask the user to guess the number,
// then tell them whether they guessed too low, too high, or exactly right.
// 8 :- Write a program that takes a list of numbers for example a = [5, 10, 15, 20, 25]
// and makes a new list of only the first and last elements of the given
// list. For practice, write this code inside a function.
// 9 :-  Write a program (function) that takes a list and returns a new list
// that contains all the elements of the first list minus all the duplicates.
import 'dart:io';
import 'dart:math';

void main() {
  //1
  getUserData();
  // 3
  getDivisors();
  // 4,5,6
  getCommonListElementAndEO();
  // 7
  showGuessValueLHR();
  // 8
  getFirstAndLastElement();
  // 9
  callRemoveDuplicateDataFromList();
  //10
  getStringByUser();
  //14
  callSimpleInterestGetData();
  //16,17
  getSquareAndSRootUserInput();
  //18
  getUserInputString();
  //19
  getSplitAmount();
  //20
  getCharFromUserToCheckVC();
  //21
  getValueForMulti();
  //22
  getAreaOfCircle();
  //23
  getNameStartWithA();
  //24
  // getMapSData();
}

void getUserData() {
  int gap = 0;

  stdout.write("Please Enter Your Name : ");
  String name = getString();
  stdout.write("Please Enter Your Age : ");
  int age = getIntegerValue();

  gap = 100 - age;
  // print(gap);
  print("Your Name is $name and $gap years you have to be 100 years old. \n");
}

void getDivisors() {
  stdout.write(
      "Please enter a number to find  how many number can be divisors : ");
  int number = getIntegerValue();
  List<int> listDivisors = [];

  for (int i = 1; i <= 100; i++) {
    if (number % i == 0) {
      listDivisors.add(i);
    }
  }
  print("$number Divisors by $listDivisors \n");
}

void getCommonListElementAndEO() {
  List<int> list1 = [
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    0,
    10,
    11,
    12,
    23,
    34,
    56,
    67,
    78,
    102,
    105,
    205,
    200,
    13,
    12,
    9,
    0,
  ];
  List<int> list2 = [
    1,
    12,
    13,
    2,
    3,
    6,
    22,
    34,
    56,
    78,
    90,
    100,
    50,
    60,
    43,
    67,
    100,
    102,
    109,
    200,
    201,
    105,
    107,
    102,
    109,
    200
  ];
  List<int> listOfCommonElements = [];
  List<int> listEven = [];
  List<int> listOdd = [];
  listOfCommonElements =
      list2.where((element1) => list1.contains(element1)).toSet().toList();

  print(
      "List1 == 1,2,3,4,5,6,7,8,9,0,10,11,12,23,34,56,67,78,102,105,205,200,13,12,9,0, ");
  print(
      "List2 ==   1,12,13,2,3,6,22,34,56,78,90,100,50,60,43,67,100,102,109,200,201,105,107,102,109,200");
  print("Common Elements are : $listOfCommonElements\n");

  listEven = listOfCommonElements.where((element) => element.isEven).toList();
  listOdd = listOfCommonElements.where((element) => element.isOdd).toList();

  print("Print Even and Odd elements from above list elements :   ");
  print("Even numbers are : $listEven");
  print("Odd numbers are : $listOdd\n");
}

void showGuessValueLHR() {
  int gap = 0;
  //get Random number by using Random Class
  Random randomNumber = Random(); //Create object of random class type Random
  int generatedNo = randomNumber.nextInt(100);

  stdout.write("Please enter guess no. : ");
  int getUserGuessValue = getIntegerValue();

  gap = getUserGuessValue - generatedNo;

  if (gap.abs() > 0 && gap.abs() <= 50) {
    print("Your guess is  High \n");
  } else if (gap.abs() > 50 || gap.abs() > 50 && gap.abs() <= 100) {
    print("Your guess is level Low \n");
  } else if (gap == gap) {
    print("Congratulations your guess is Exactly Right \n");
  }
  print("Show Random number generated by system is: $generatedNo");
  print("User Guess Number : $getUserGuessValue");
  print("Gap between numbers  : $gap \n");
}

void getFirstAndLastElement() {
  List<int> listData = [
    5,
    10,
    15,
    20,
    25,
    30,
    35,
    40,
    45,
    50,
    55,
    60,
    65,
    70,
    75,
    80,
    85,
    90,
    95
  ];
  List<int> newList = [];

  newList.add(listData.first);
  newList.add(listData.last);
  print(
      "List is ==> [5,10,15,20,25,30,35,40,45,50,55,60,65,70,75,80,85,90,95]");
  print("First and Last element of listData : $newList\n");
}

void callRemoveDuplicateDataFromList() {
  List<int> finalList = removeDuplicateDataFromList();
  print("After remove duplicate values list have elements are : - $finalList");
}

List<int> removeDuplicateDataFromList() {
  List<int> listElements = [];
  stdout.write(
      "Enter value u want to add in list and make sure some values are Duplicate Input 20 values  : ");
  for (int i = 0; i < 15; i++) {
    int values = getIntegerValue();
    listElements.add(values);
  }
  print("Values are : $listElements");
  return listElements.toSet().toList();
}

void getStringByUser() {
  print("Please enter long string : ");
  String getString1 = getString();
  String backWordSentence = backwordsOrderString(getString1);
  print('result :-  $backWordSentence\n');
}

String backwordsOrderString(String longString) {
  List<String> sentenceList = [];
  sentenceList = longString.split(' ');
  return sentenceList.reversed.join(' ').toString();
}

//incomplete 11 assignment
void gameCowAndBullCount() {
  int c = 0, b = 0; //where i count for cows and j is for bull
  Random objRandom = Random();
  int generatedInt4 = objRandom.nextInt(9999);
  print('Random number$generatedInt4');
}

void callSimpleInterestGetData() {
  stdout.write("Enter Principle Amount : ");
  int pAmount = getIntegerValue();
  stdout.write("Enter Time/Years ");
  int time = getIntegerValue();
  stdout.write("Enter rate of interest : ");
  double rate = getIntegerValue().toDouble();
  var result = getSimpleInterest(pAmount, time, rate);
  print("Simple Interest is : $result\n");
}

double getSimpleInterest(int principleAmount, int time, double rate) {
  var result = (principleAmount * rate * time) / 100;
  return result;
}

void getSquareAndSRootUserInput() {
  stdout.write("Please enter a value find Square : ");
  int number = getIntegerValue();
  var result = pow(number, 2);
  var getSquareRoot = sqrt(number);
  print(
      "$number Square is $result and Square Root is ${getSquareRoot.toStringAsFixed(8)}\n");
}

void getUserInputString() {
  var typedString = '     Supriya arora is my name     '.trim();
  print("$typedString\n");
}

void getSplitAmount() {
  stdout.write("Enter Total amount : ");
  int amount = getIntegerValue();

  stdout.write("Enter how many people split the amount :  ");
  int person = getIntegerValue();

  if (person > 1) {
    int splitAmount = amount ~/ person;
    print("Each person have to pay $splitAmount");
  }
}

void getCharFromUserToCheckVC() {
  stdout.write("Enter Letter to check is Vowel or Consonant : ");
  String checkLetter = getString();
  letterIsVC(checkLetter);
}

void letterIsVC(String letter) {
  if (letter == 'a' ||
      letter == 'A' ||
      letter == 'e' ||
      letter == 'E' ||
      letter == 'i' ||
      letter == 'I' ||
      letter == 'o' ||
      letter == 'O' ||
      letter == 'u' ||
      letter == 'U') {
    print("$letter is Vowel");
  } else {
    print("$letter is Consonant");
  }
}

void getValueForMulti() {
  stdout.write("Enter value u want to print Table : ");
  int result = getIntegerValue();
  multiplicationTable(result);
}

void multiplicationTable(int tableOf) {
  for (int i = 1; i <= 10; i++) {
    print("table of $tableOf * $i  = ${tableOf * i}   ");
  }
}

void getAreaOfCircle() {
  stdout.write("Enter radius value : ");
  int r = getIntegerValue();
  var result = pi * r * r;
  print("Area of circle is : $result");
}

void getNameStartWithA() {
  List<String> names = [
    'Aashi',
    'Supriya',
    'Avinash',
    'Priya',
    'Aarohi',
    'Aishvi',
    'Yash'
  ];
  var newList = names.where((element) => element.startsWith('A')).toList();
  print(newList);
}

//notComplete
void getMapSData() {
  Map<String, String> mapData = {'Name': 'Riya', 'Phon': '9828281029'};
  print(mapData.keys); //create list of map
}

//Get User Data From Console
String getString() => (stdin.readLineSync().toString());

int getIntegerValue() => (int.parse(stdin.readLineSync().toString()));
